#ifndef SAM_BELLIVEAU_MUSIC_LIBRARY
#define SAM_BELLIVEAU_MUSIC_LIBRARY

struct song_literal
{
    const char* artist;
    const char* title;
};

const struct song_literal MUSIC_LIBRARY[] =
{
    {"Molchat Doma", "Судно (Борис Рижий)"},
    {"Metro Boomin", "Space Cadet (feat. Gunna)"},
    {"Joji", "worldstar money (interlude)"},
    {"SALES", "Chinese New Year"},
    {"347aidan", "Dancing in My Room"},
    {"Sub Urban", "Cradles"},
    {"Thundercat", "Funny Thing"},
    {"Juice WRLD", "Let Me Know (I Wonder Why Freestyle)"},
    {"The Kid LAROI", "WITHOUT YOU"},
    {"Grover Washington, Jr.", "Just the Two of Us (feat. Bill Withers)"},
    {"Sia", "Snowman"},
    {"The Kid LAROI", "SO DONE"},
    {"Pharmacist", "North Memphis"},
    {"Juice WRLD", "Used To"},
    {"L.Dre", "Steven Universe"},
    {"Wilbur Soot", "Your New Boyfriend"},
    {"The Neighbourhood", "Sweater Weather"},
    {"Blonde Redhead", "For the Damaged Coda"},
    {"Dream", "Roadtrip"},
    {"ElyOtto", "SugarCrash!"},
    {"Juice WRLD", "All Girls Are The Same"},
    {"AURORA", "Runaway"},
    {"Keith Ape", "Achoo"},
    {"Kendrick Lamar", "Money Trees"},
    {"WILLOW", "Wait a Minute!"},
    {"alt-J", "Breezeblocks"},
    {"Harmless", "Swing Lynn"},
    {"Glass Animals", "Take A Slice"},
    {"Fitz and The Tantrums", "Out of My League"},
    {"Tame Impala", "The Less I Know The Better"},
    {"Beach Bunny", "Cloud 9"},
    {"Arctic Monkeys", "Why'd You Only Call Me When You're High?"},
    {"Edward Sharpe & The Magnetic Zeros", "Home"},
    {"Juice WRLD", "Lucid Dreams"},
    {"Coyote Theory", "This Side of Paradise"},
    {"Kid Cudi", "Mr. Rager"},
    {"XXXTENTACION", "NUMB"},
    {"Justice", "D.A.N.C.E"},
    {"Roar", "I Can't Handle Change"},
    {"Gym Class Heroes", "Cupid's Chokehold / Breakfast in America"},
    {"XXXTENTACION", "Jocelyn Flores"},
    {"XXXTENTACION", "Everybody Dies In Their Nightmares"},
    {"Juice WRLD", "Lean Wit Me"},
    {"Verzache", "Needs"},
    {"Verzache", "The Loser"},
    {"Mild High Club", "Homage"},
    {"Swell", "I'm Sorry"},
    {"Mother Mother", "Burning Pile"},
    {"The Weeknd", "Blinding Lights"},
    {"Ski Mask The Slump God", "BabyWipe"},
    {"Kendrick Lamar", "Alright"},
    {"Kendrick Lamar", "DNA."},
    {"Kendrick Lamar", "ELEMENT."},
    {"Kendrick Lamar", "King Kunta"},
    {"Kendrick Lamar", "Bitch, Don’t Kill My Vibe"},
    {"Kendrick Lamar", "XXX. FEAT. U2."},
    {"Lil Uzi Vert", "20 Min"},
    {"Kendrick Lamar", "The Art of Peer Pressure"},
    {"Kendrick Lamar", "m.A.A.d city"},
    {"Kendrick Lamar", "Backseat Freestyle"},
    {"The Neighbourhood", "Greetings from Califournia"},
    {"$uicideboy$", "...And to Those I Love, Thanks for Sticking Around"},
    {"Glass Animals", "Heat Waves"},
    {"Kendrick Lamar", "Sing About Me, I'm Dying Of Thirst"},
    {"Juice WRLD", "Out My Way"},
    {"Ark Patrol", "Let Go"},
    {"Mr.Kitty", "After Dark"},
    {"Lil Peep", "Star Shopping"},
    {"Joji", "Run"},
    {"Joji", "Sanctuary"},
    {"Juice WRLD", "Armed And Dangerous"},
    {"Joji", "YEAH RIGHT"},
    {"Lonely God", "Marlboro Nights"},
    {"Juice WRLD", "Syphilis"},
    {"Joji", "Gimme Love"},
    {"Juice WRLD", "10 Feet"},
    {"Juice WRLD", "Empty"},
    {"Breakbot", "Baby I'm Yours - feat. Irfrane"},
    {"Matt Maltese", "As the World Caves In"},
    {"Lil Peep", "Save That Shit"},
    {"Bo Burnham", "All Eyes On Me"},
    {"Juice WRLD", "Legends"},
    {"Lil Peep", "beamer boy"},
    {"Wallows", "Are You Bored Yet? (feat. Clairo)"},
    {"Juice WRLD", "Smile (with The Weeknd)"},
    {"Ski Mask The Slump God", "Unbothered"},
    {"Ski Mask The Slump God", "Take A Step Back"},
    {"Ski Mask The Slump God", "Foot Fungus"},
    {"Olivia Rodrigo", "good 4 u"},
    {"Ski Mask The Slump God", "Nuketown (feat. Juice WRLD)"},
    {"Ski Mask The Slump God", "Faucet Failure"},
    {"Ski Mask The Slump God", "Catch Me Outside"},
    {"Ski Mask The Slump God", "Merlin’s Staff"},
    {"Ski Mask The Slump God", "Dr. Suess"},
    {"Ski Mask The Slump God", "The Matrix"},
    {"Ski Mask The Slump God", "ADMIT IT"},
    {"Adventure Time", "Island Song"},
    {"Ski Mask The Slump God", "Reborn To Rebel"},
    {"Ski Mask The Slump God", "The Human Centipede"},
    {"Ski Mask The Slump God", "Durgaflowz"},
    {"Juice WRLD", "Hide (feat. Seezyn)"},
    {"Beach House", "Space Song"},
    {"Tyler, The Creator", "WUSYANAME (feat. Youngboy Never Broke Again & Ty Dolla $ign)"},
    {"DJ Scheme", "How You Feel? (Freestyle) (feat. Lil Yachty & Ski Mask The Slump God)"},
    {"Juice WRLD", "Fighting Demons"},
    {"Juice WRLD", "Bad Energy"},
    {"Juice WRLD", "Blood On My Jeans"},
    {"Juice WRLD", "Wishing Well"},
    {"Juice WRLD", "Can't Die"},
    {"Home", "Resonance"},
    {"Juice WRLD", "I'm Still"},
    {"Juice WRLD", "End Of The Road"},
    {"Juice WRLD", "I'll Be Fine"},
    {"Home", "We're Finally Landing"},
    {"XXXTENTACION", "Look At Me!"},
    {"Lil Peep", "Falling Down - Bonus Track"},
    {"Juice WRLD", "Maze"},
    {"Steve Lacy", "Dark Red"},
    {"Lil Uzi Vert", "The Way Life Goes (feat. Oh Wonder)"},
    {"Kanye West", "Moon"},
    {"Baby Keem", "family ties (with Kendrick Lamar)"},
    {"girl in red", "we fell in love in october"},
    {"girl in red", "bad idea!"},
    {"ScHoolboy Q", "Collard Greens"},
    {"Juice WRLD", "Robbery"},
    {"Ski Mask The Slump God", "DAPPER DAN"},
    {"Ski Mask The Slump God", "COOLEST MONKEY IN THE JUNGLE"},
    {"Juice WRLD", "Rich And Blind"},
    {"Joji", "SLOW DANCING IN THE DARK"},
    {"The Neighbourhood", "Prey"},
    {"The Neighbourhood", "Stargazing"},
    {"The Neighbourhood", "Afraid"},
    {"The Neighbourhood", "You Get Me So High"},
    {"The Neighbourhood", "Reflections"},
    {"The Neighbourhood", "Compass"},
    {"The Neighbourhood", "Everybody's Watching Me (Uh Oh)"},
    {"Juice WRLD", "Candles"},
    {"Post Malone", "rockstar (feat. 21 Savage)"},
    {"Post Malone", "Better Now"},
    {"Post Malone", "Psycho (feat. Ty Dolla $ign)"},
    {"Post Malone", "Congratulations"},
    {"Joji", "SLOW DANCING IN THE DARK"},
    {"Kanye West", "Father Stretch My Hands Pt. 1"}
};

const int MUSIC_LIBRARY_SIZE = sizeof(MUSIC_LIBRARY)/sizeof(*MUSIC_LIBRARY);

#endif